import Link from "next/link";
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'About',
    description: 'Generated by create next app',
    icons: {
      icon: '/favicon.ico',
    },
  };
  
  export const viewport = {
    width: 'device-width',
    initialScale: 1,
  };

export default function About() {
  return (
    <>
      <h1>About</h1>
      <Link href="/"> Link to Home Page</Link>
    </>
  );
}
